# Enable Dependabot version updates
# https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-dependabot-version-updates

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    commit-message:
      prefix: 'chore(deps): '
    open-pull-requests-limit: 5
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
      actions-major:
        update-types:
          - major
    labels:
      - github-actions
      - dependencies
      - dependabot

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    target-branch: main
    commit-message:
      prefix: 'chore(deps): '
    open-pull-requests-limit: 5
    groups:
      nuget-minor:
        update-types:
          - minor
          - patch
      nuget-major:
        update-types:
          - major
    labels:
      - nuget
      - dependencies
      - dependabot
