name: code quality

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  schedule:
    - cron: "18 6 * * 1" # every Monday at 06:18 UTC

  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp"]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Build net5.0 targets
        run: dotnet build --framework net5.0

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
