name: code analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "18 6 * * 1" # Every Monday at 06:18 UTC
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp"]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Inject target dotnet version into environment
        run: echo "DOTNET_GLOBAL_VERSION=net$(cat global.json | jq --raw-output '.sdk.version' | cut -c1-3)" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Restore dependencies
        run: dotnet restore --verbosity normal

      - name: Build net${{ env.DOTNET_GLOBAL_VERSION }} targets
        run: dotnet build --no-restore --framework net${{ env.DOTNET_GLOBAL_VERSION }} /p:UseSharedCompilation=false

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
