name: update dotnet sdk

on:
  schedule:
    - cron: "23 1 * * 2" # every Tuesday at 01:23 UTC

  workflow_dispatch:

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2.3.4

      - name: Run Update .NET SDK
        uses: martincostello/update-dotnet-sdk@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
